gas_service_app/urls.py
from django.urls import path

from . import views

app_name = "first"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("customer", views.customer, name="customer"),
    path("submit_request", views.submit_request, name="submit_request"), #done with javaScript
    path("submitted_requests", views.submitted_requests, name="request_tracking"), 
    path("view_request/<int:pk>", views.view_request, name="view_request"),
    path("resolved_requests", views.resolved, name="resolved"),
    path("message_csr/<int:pk>", views.message_csr, name="message_csr"),
    path("reopen_request/<int:pk>", views.reopen_request, name="reopen")
]

gas_utility/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("gas_service_app.urls")),
    path('support/', include('support.urls')),  # Include the support app's URLs
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/urls.py
from django.urls import path
from . import views

app_name = "support"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    # path("view_request/<int:pk>", views.view_request, name="view_request"),
    path("edit_request/<int:pk>", views.edit_request, name="edit_request"),
    path("message_csr/<int:pk>", views.message_csr, name="message_csr"),
    path("resolved_requests", views.resolved, name="resolved")
]

gas_service_app/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

SERVICE_TYPES = (
        ('Cylinder did not arrived', 'Cylinder did not arrived'),
        ('Billing Related', 'Billing Related'),
        ('Others', 'Others'),    
    )

STATUS = (
        ('Submitted', 'Submitted'),
        ('Pending', 'Pending'),
        ('Resolved', 'Resolved')
)

ROLES = (
    ('admin', 'admin'),
    ('customer', 'customer')
)

phone_regex = RegexValidator(
    regex=r'^\d{10}$',
    message="Phone number should be of 10 digits."
)

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(validators=[phone_regex], max_length=10, blank=True)

    def __str__(self):
        return f"Customer: {self.user}"


class ServiceRequest(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="service_request")
    request_type = models.CharField(max_length=100, choices=SERVICE_TYPES)
    details = models.TextField()
    attachment = models.FileField(upload_to='attachments', blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS, default="Submitted")
    submitted_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.customer}'s complaint"
    
    def save(self, *args, **kwargs):
        if self.status == "Submitted" or self.status == "Pending":
            self.resolved_at = None  # Set resolved_at to None if status is Submitted
        super().save(*args, **kwargs)

class Message(models.Model):
    related_to = models.ForeignKey(ServiceRequest, on_delete=models.CASCADE, related_name="complaint_messages")
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender} : {self.related_to}"

gas_service_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Customer, ServiceRequest, Message

class Customerform(ModelForm):
    class Meta:
        model = Customer
        fields = ('phone_number',)

        labels={
            'phone_number':"",
        }

        widgets ={
            'phone_number' : forms.TextInput(attrs={'placeholder': "Register your mobile number and",'cols': 50, 'rows': 1 ,'class': 'form-control'}),
        }

class ServiceRequestForm(ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ('request_type', 'details', 'attachment', 'status')

        labels={
            'request_type' : "Complaint Type",
            'details' : 'Description',
            'attachment' : 'Attach your file here',
            'status' : 'Status'
        }

        widgets = {
            'request_type': forms.Select(attrs={'class': 'form-select'}),
            'details': forms.Textarea(attrs={'class': 'form-control'}),
            'attachment': forms.FileInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

class Messageform(ModelForm):
    class Meta:
        model = Message
        fields = ('content',)        

        labels = {
            'content': ""
        }

        widgets= {
            'content': forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : "Message our customer support representative"})
        }

gas_service_app/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.core.exceptions import ValidationError
from .decorators import unauth_user, allowed_users
from django.contrib.auth.models import Group
from django import forms
from django.http import JsonResponse
import json

#forms
from .forms import Customerform, ServiceRequestForm, Messageform

#Models
from .models import Customer, ServiceRequest, User, Message

# Create your views here.

@unauth_user
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "gas_service_app/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            customer_group, created = Group.objects.get_or_create(name='customer')
            user = User.objects.create_user(username, email, password)
            user.save()
            user.groups.add(customer_group)
        except IntegrityError:
            return render(request, "gas_service_app/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("first:index"))
    else:
        return render(request, "gas_service_app/register.html")

@unauth_user
def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("first:index"))
        else:
            return render(request, "gas_service_app/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "gas_service_app/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("first:login"))

@login_required(login_url='first:login')
@allowed_users(allowed_roles=['customer'])
def index(request):
    all_customers = Customer.objects.all()
    form = ServiceRequestForm()
    # check if user is already a customer
    is_registered = any(customer.user == request.user for customer in all_customers)

    
    
    form.fields['status'].widget = forms.HiddenInput()
    return render(request, 'gas_service_app/index.html', {
        'customerForm': Customerform(),
        'submit_request' : form,
        'all_customer': all_customers,
        'is_registered': is_registered  
    })

#Registering Customer with phone number
@login_required(login_url='first:login')
@allowed_users(allowed_roles=['customer'])
def customer(request):
    print(request)
    if request.method == "POST":
            form = Customerform(request.POST)
            if form.is_valid():
                form.instance.user = request.user
                form.instance.phone_number = form.cleaned_data["phone_number"]
                form.save()
                messages.add_message(request, messages.SUCCESS, "Customer Registered Successfully")
                return redirect('first:index')
                #Value Error issued has not been solved

#Saving Customer's Complaint
@login_required(login_url='first:login')
@allowed_users(allowed_roles=['customer'])
def submit_request(request):
    customer = Customer.objects.get(user=request.user)
    if request.method == 'POST':
        files = request.FILES.get('attachment')
        #print("files------>", files)
        data = json.loads(json.dumps(request.POST))
        x = ServiceRequest(customer=customer, request_type=data["request_type"], details = data["details"], attachment=files) 
        x.save()
        messages.add_message(request, messages.SUCCESS, "Your compliant has been registered successfully")
        return redirect("first:index")

    return JsonResponse({'error': 'Invalid request method'})

@login_required(login_url="first:login")
@allowed_users(allowed_roles=['customer'])
def submitted_requests(request):
    try:
        customer = Customer.objects.get(user=request.user)
        track = ServiceRequest.objects.filter(customer=customer, status="Submitted").order_by('-submitted_at')
        return render(request, 'gas_service_app/track_requests.html', {
            'requests' : track
        })
    except:
        return HttpResponse("Register your phone number") 

@login_required(login_url="first:login")
@allowed_users(allowed_roles=['customer'])
def view_request(request, pk):                   
    view_request = ServiceRequest.objects.get(pk=pk)
    messages = Message.objects.filter(related_to=pk).order_by('-timestamp')
    return render(request, "gas_service_app/view_request.html", {
        "request" : view_request,
        "message_form" : Messageform,
        "all_messages_related_to_complaint" : messages
    })

@login_required(login_url="first:login")
@allowed_users(allowed_roles=['customer'])
def resolved(request):
    # print("Resolved")
    try:
        user = Customer.objects.get(user=request.user)
        resolved = ServiceRequest.objects.filter(customer=user, status="Resolved")
        # print("Resolved 2")
        return render(request, "gas_service_app/resolved.html", {
            'resolved' : resolved
    })
    except:
        return HttpResponse("Register your phone number")

@login_required(login_url="first:login")
@allowed_users(allowed_roles=['customer'])
def reopen_request(request, pk):
    get_service = ServiceRequest.objects.get(id=pk)
    get_service.status = "Submitted"
    get_service.save()
    # print(get_service.status) 
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def message_csr(request, pk):
    if request.method == "POST":
        data = json.loads(request.body)
        # print("data---------->",data)
        related_to = ServiceRequest.objects.get(id=pk)
        sender = request.user
        content = data['message']
        timestamp = timezone.now()
        x = Message(related_to=related_to, sender=sender, content=content, timestamp=timestamp)
        x.save()
        return JsonResponse({"message" : "success"})

gas_service_app/templates/gas_service_app/index.html
{% extends "gas_service_app/layout.html" %}

{% block body %}

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible">
                <a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    
    {% if is_registered %}
        <form method="post" enctype="multipart/form-data" action="{% url 'first:submit_request' %}" id="myForm">
            <h2>Submit complaint</h2>
            {% csrf_token %}
            <p>Request Type: {{ submit_request.request_type }} </p>
            <p>Describe what problem you are facing in detail: {{ submit_request.details }} </p>
            <p name="picture">
                <span style="color: rgb(192, 19, 19);"> *Only JPEGs and PNGs are allowed</span> 
                {{submit_request.attachment }} 
            </p>
            <button type="submit" class="btn btn-primary">Submit Request</button>
        </form>
    {% else %}
        <form action="{% url 'first:customer' %}" method="POST">
            {% csrf_token %}
            {{ customerForm.as_p }}
            <button type="submit" class="btn btn-outline-primary btn-sm">Become our customer</button>
        </form>
    {% endif %}


{% endblock %}

gas_service_app/templates/gas_service_app/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Customer Care{% endblock %}</title>
        <link href="{% static 'gas_service_app/styles.css' %}" rel="stylesheet">
        <script src = "{% static 'gas_service_app/index.js' %}"></script>

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
        <!-- Bootstrap link -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <body>

        <nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'first:index' %}">Customer Care</a>
          
            <div class="ml-auto">
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first:resolved' %}">Resolved complaints</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first:request_tracking' %}">Submitted complaints</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="login" href="{% url 'first:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        <br>
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    </body>
</html>

gas_service_app/templates/gas_service_app/login.html
{% extends "gas_service_app/layout.html" %}
{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'first:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group mb-3">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group mb-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-dark" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'first:register' %}">Register here.</a>

{% endblock %}

gas_service_app/templates/gas_service_app/register.html
{% extends "gas_service_app/layout.html" %}
{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'first:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group mb-3">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>

        <div class="form-group mb-3">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>

        <div class="form-group mb-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>

        <div class="form-group mb-3">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>

        <input class="btn btn-dark" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'first:login' %}">Log In here.</a>

{% endblock %}

gas_service_app/templates/gas_service_app/resolved.html
{% extends "gas_service_app/layout.html" %}
{% block body %}

<h5>Resolved complaints</h5>
    <div class="resolved">
        {% for request in resolved %}
        <div class="request card mb-3">
            <div class="card-body">
                <h3 class="card-title">{{ request.request_type }}</h3>
                <p class="card-text">Details: {{ request.details }}</p>
                <p class="card-text">Status: {{ request.status }}</p>
                <p class="card-text">Submitted Date: {{ request.submitted_at }}</p>
                <p class="card-text">Resolved Date: {{ request.resolved_at }}</p>
                {% if request.attachment %}
                    <p class="card-text">Attachment: <a href="{{ request.attachment.url }}" target="_blank">{{ request.attachment }}</a></p>
                {% endif %}
                <a href="{% url 'first:reopen' request.id %}" class="btn btn-dark">Re-open</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

gas_service_app/templates/gas_service_app/submit_request.html
{% extends "gas_service_app/layout.html" %}
{% block body %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <h2>Submit Service Request</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="request_type">Request Type:</label>
        <input type="text" name="request_type" id="request_type" required><br>
        <label for="details">Details:</label>
        <textarea name="details" id="details" required></textarea><br>
        <label for="attachment">Attachment:</label>
        <input type="file" name="attachment" id="attachment"><br>
        <button type="submit">Submit Request</button>
    </form>
    

{% endblock %}

gas_service_app/templates/gas_service_app/track_requests.html
{% extends "gas_service_app/layout.html" %}
{% block body %}

<h5>Submitted Requests</h5>
{% for request in requests %}
  <div class="request card mb-3">
      <div class="card-body">
          <h3 class="card-title">{{ request.request_type }}</h3>
          <p class="card-text">Details: {{ request.details }}</p>
          <p class="card-text">Status: {{ request.status }}</p>
          <p class="card-text">Submitted Date: {{ request.submitted_at }}</p>
          <p class="card-text">Resolved Date: {{ request.resolved_at | default:"Not resolved yet" }}</p>

          {% if request.attachment %}
                <p class="card-text">Attachment: <a href="{{ request.attachment.url }}" target="_blank">{{ request.attachment.name }}</a></p>
          {% endif %}
          <!-- <a href="{% url 'first:view_request' request.pk %}" class="btn btn-dark"> View </a> -->
          <a onclick="view_request( {{ request.id }} )" class="btn btn-dark"> View </a>
      </div>
  </div>
{% endfor %}


{% endblock %}

gas_service_app/templates/gas_service_app/view_request.html
{% extends "gas_service_app/layout.html" %}
{% block body %}
  <div class="request card mb-3">
      <div class="card-body">
          <h3 class="card-title">{{ request.request_type }}</h3>
          <p class="card-text">Details: {{ request.details }}</p>
          <p class="card-text">Status: {{ request.status }}</p>
          <p class="card-text">Submitted Date: {{ request.submitted_at }}</p>
          <p class="card-text">Resolved Date: {{ request.resolved_at | default:"Not resolved yet" }}</p>
          {% if request.attachment %}
              <p class="card-text">Attachment: <a href="{{ request.attachment.url }}" target="_blank">{{ request.attachment | default:"No Attachment" }}</a></p>
          {% endif %}
      </div>
  </div>

  <div>
    <form method="POST" >
      {% csrf_token %}
      <p id="content">{{ message_form.content }}</p>
      <button type="submit" onclick="message( {{ request.id }}, event )" class="btn btn-dark">Message</button>
    </form>
  </div>

  <br>
  <h5>All messages</h5>
  <div class="card">
    {% for message in all_messages_related_to_complaint %}
      <div class="card-header">
        <p>{{message.sender | upper}} &nbsp;<small>{{ message.timestamp }}</small></p>
      </div>
      <div class="card-body">
        <p> {{message.content}} </p> 
      </div>
      <br>
    {% endfor %}
  </div>

{% endblock %}