gas_utility/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("gas_service_app.urls")),
    path('support/', include('support.urls')),  # Include the support app's URLs
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/urls.py
from django.urls import path
from . import views

app_name = "support"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    # path("view_request/<int:pk>", views.view_request, name="view_request"),
    path("edit_request/<int:pk>", views.edit_request, name="edit_request"),
    path("message_csr/<int:pk>", views.message_csr, name="message_csr"),
    path("resolved_requests", views.resolved, name="resolved")
]

support/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from gas_service_app.models import ServiceRequest
from gas_service_app.forms import ServiceRequestForm
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from .decorators import allowed_users, unauth_user
from django.contrib.auth.decorators import login_required
from gas_service_app.models import Message
from django.contrib.auth.models import Group
from gas_service_app.forms import Messageform
from gas_service_app.models import User
from django.db.models import Q
from django import forms
import json
# Create your views here.
@unauth_user
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "support/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            support_group, created = Group.objects.get_or_create(name='support')
            user = User.objects.create_user(username, email, password)
            user.save()
            user.groups.add(support_group)
        except IntegrityError:
            return render(request, "support/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("support:index"))
    else:
        return render(request, "support/register.html")

@unauth_user
def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("support:index"))
        else:
            return render(request, "support/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "support/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("support:login"))

@login_required(login_url="support:login")
@allowed_users(allowed_roles=['support'])
def index(request):
    requests = ServiceRequest.objects.filter(Q(status="Submitted") | Q(status="Pending")).order_by('-submitted_at')
    return render(request, "support/index.html", {
        'requests' : requests
    })

@login_required(login_url="support:login")
@allowed_users(allowed_roles=['support'])
def edit_request(request, pk):
    service = get_object_or_404(ServiceRequest, pk=pk)
    attachment = service.attachment
    # # print(service.request_type)
    # # print(service.customer.id, service.customer.user.id)
    if request.method == 'POST':
        form = ServiceRequestForm(request.POST, instance=service)
        if form.is_valid():
            instance = form.save(commit=False)  
            instance.request_type = service.request_type
            instance.details = service.details
            instance.resolved_at = timezone.now()  
            instance.status = form.cleaned_data["status"]
            instance.save()  
            return redirect('support:index')
        else:
            return HttpResponse(form.errors)
    else:  
        form = ServiceRequestForm(instance=service)
        form.fields['request_type'].widget = forms.HiddenInput()
        form.fields['details'].widget.attrs['readonly'] = True
        form.fields['attachment'].widget = forms.HiddenInput()

    return render(request, "support/edit_request.html", { 
        'form' : form,
        'service' : service,
        'attachment' : attachment,
        'message_form' : Messageform(),
        'all_messages_related_to_complaint' : Message.objects.filter(related_to=service).order_by('-timestamp')
    })

@login_required(login_url="support:login")
@allowed_users(allowed_roles=['support'])
def resolved(request):
    resolved = ServiceRequest.objects.filter(status="Resolved")
    return render(request, "support/resolved.html", {
        'resolved' : resolved
})


def message_csr(request, pk):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            #print("data---------->",data)
            related_to = ServiceRequest.objects.get(id=pk)
            sender = request.user
            content = data['message']
            timestamp = timezone.now()
            x = Message(related_to=related_to, sender=sender, content=content, timestamp=timestamp)
            x.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except:
            return HttpResponse("Error 404")

support/templates/support/edit_request.html
{% extends 'support/layout.html' %} 
{% block body %}
<div class="card">
  <div class="card-header">
    <h5>{{ service.customer | upper}}</h5>
  </div>
  <div class="card-body">
    <form method="POST">
      {% csrf_token %}
      {{ form.request_type }}
      Complaint : {{ service.request_type }}
      <p></p>
      Details: {{ form.details }}
      <p></p>
      {% if attachment %}
      Attachment: <a href="{{ attachment.url }}"> {{ attachment }} </a>
      {% endif %}
      <p></p>
      Status: {{ form.status }}
      <p></p>
      <button  type="submit" class="btn btn-primary">Save Changes</button>
   </form>
   <small><a href="{% url 'support:index' %}">Back to Requests</a></small>
  </div>
</div>

<br>
<div>
  <form  method="POST" >
    {% csrf_token %}
    <p id="content">{{ message_form.content }}</p>
    <button type="submit" onclick="message({{service.id}}, event)" class="btn btn-dark">Message</button>
  </form>
</div>

<br>
<h5>All messages</h5>
<div class="card">
  {% for message in all_messages_related_to_complaint %}
    <div class="card-header">
      <p>{{message.sender}} <small>{{ message.timestamp }}</small></p>
    </div>
    <div class="card-body">
      {{message.content}} 
    </div>
    <br>
  {% endfor %}
</div>

{% endblock %}

support/templates/support/index.html
{% extends "support/layout.html" %}
{% block body %}

<h5>Submitted Complaints</h5>
{% if requests %}
    {% for request in requests %}
        <div class="request card mb-3">
            <div class="card-body">
                <h4 class="card-title">{{ request.customer }}</h4>
                <p class="card-text">Request Type: {{ request.request_type }}</p>
                <p class="card-text">Details: {{ request.details }}</p>
                <p class="card-text">Status: {{ request.status }}</p>
                <p class="card-text">Submitted Date: {{ request.submitted_at }}</p>
                <p class="card-text">Resolved Date: {{ request.resolved_at | default:"Not resolved yet" }}</p>
                
                
                {% if request.attachment %}
                    <p class="card-text">Attachment: <a href="{{ request.attachment.url }}" target="_blank">{{ request.attachment }}</a></p>
                {% endif %}
                <a href="{% url 'support:edit_request' request.pk %}" class="btn-btn dark">View Complaint</a>
            </div>
        </div>
    {% endfor %}
{% else %}
    <h3>No tickets</h3>
{% endif %}

{% endblock %}

support/templates/support/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Customer Care{% endblock %}</title>
        <link href="{% static 'support/styles.css' %}" rel="stylesheet">
        <script src = "{% static 'support/index.js' %}"></script>
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
        <script src="{% static 'support/index.js' %}"></script>
        <!-- Bootstrap link -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>
    <body>
        <nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'support:index' %}">Customer Care</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'support:resolved' %}">Resolved complaints</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'support:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'support:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="login" href="{% url 'support:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        <br>
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    </body>
</html>

support/templates/support/login.html
{% extends "support/layout.html" %}
{% block body %}

    <h2>Support Team: Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'support:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group mb-3">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group mb-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-dark" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'support:register' %}">Register here.</a>

{% endblock %}

support/templates/support/register.html
{% extends "support/layout.html" %}
{% block body %}

    <h2>Support Team: Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'support:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group mb-3">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>

        <div class="form-group mb-3">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>

        <div class="form-group mb-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>

        <div class="form-group mb-3">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>

        <input class="btn btn-dark" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'support:login' %}">Log In here.</a>

{% endblock %}

support/templates/support/resolved.html
{% extends "support/layout.html" %}
{% block body %}

<h5>Resolved complaints</h5>
    <div class="resolved">
        {% for request in resolved %}
        <div class="request card mb-3">
            <div class="card-body">
                <h3 class="card-title">{{ request.customer.user | upper }}</h3>
                <p class="card-text">{{ request.request_type }}</p>
                <p class="card-text">Details: {{ request.details }}</p>
                <p class="card-text">Status: {{ request.status }}</p>
                <p class="card-text">Submitted Date: {{ request.submitted_at }}</p>
                <p class="card-text">Resolved Date: {{ request.resolved_at }}</p>
                {% if request.attachment %}
                    <p class="card-text">Attachment: <a href="{{ request.attachment.url }}" target="_blank">{{ request.attachment }}</a></p>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}